services:
  db:
    image: gardinfernando/atividade2-db
    container_name: atividade2-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: atividade02
    ports:
      - "5432:5432"
