services:
  db:
    image: gardinfernando/atividade2-db
    container_name: atividade2-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atividade02
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    image: gardinfernando/atividade2-web
    container_name: atividade2-web
    ports:
      # Mapeia a porta 5000 do seu computador para a 8200 do container
      - "5000:8200" 
    # --- ADICIONE TODA ESTA SEÇÃO 'environment' ---
    environment:
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
      MYSQL_DBNAME: atividade02
      MYSQL_ADDRESS: db  # O endereço do banco é o nome do serviço 'db'
    depends_on:
      - db
