FROM python:3.9-slim

WORKDIR /app

# Instala dependências Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia a aplicação
COPY main.py .

# Executa o Flask
CMD ["python", "main.py"]
